### PR TITLE
Small Features and Bug Fixes

### PR DESCRIPTION
**Pull request by MasterFlomaster1**
I've worked on some small improvements and bug fixes:

- Added `.gitignore` file for better repository management.
- Organized and simplified code slightly.
- Added `JScrollPane` for automatic scrollbar addition when text exceeds window dimensions.
- Implemented mechanisms to prevent losing unsaved data.

Screenshot for preview:
dad1212d

### CODE REVIEW

**Comment by icancodefyi** [comment]
Dear MasterFlomaster1,

Thank you for your pull request and for the improvements you've made to the
Notepad Java application. I've reviewed the changes, and they look great!
Your efforts in organizing the code, adding the .gitignore file,
implementing the JScrollPane, and preventing data loss are much appreciated.

I will go ahead and merge your changes into the main branch. If you're
interested in collaborating on other projects, please get in touch with me.
Additionally, I have a doubt regarding this project and would appreciate
your help in resolving it.

Get Connected with me through MyInstagram
<https://www.instagram.com/zaiddddddd_16/>.

Best regards, Zaid Rakhange

**Review by icancodefyi — APPROVED** [review]

**Comment by MasterFlomaster1** [comment]
Thank you, I could answer questions via Discord messages because I don't have Instagram

**Comment by icancodefyi** [comment]
Appreciate it!
Please help with providing your discord id.
Thank you

**Comment by MasterFlomaster1** [comment]
airforceproud1488

**Comment by icancodefyi** [comment]
Request sent to the provided username

**Pull request merged**
